New branch Solution
BIN0VA/Personal-Assistant pull request #30
Opened 2024-10-10 14:32 UTC by mzLeVit

The code here provides a solution for tasks: 

Основна вимога 11: Створення файлів #13
Основна вимога 12: Сортування файлів #14
Аутентифікаційна вимога 2: Доступи файлів #24

Comments are welcomed

2024-10-10 14:51 UTC, lexhouk commented
Прошу дотримуватися узгодженого формату роботу із задачами, а саме:

1. Одна задача - один пул реквест.
2. Гілки має мати префікс `feature/` після якого слідує номер задачі і її коротка назва. Наприклад, для #13 - це `feature/13-create-files`.
3. Можна працювати і в форку але краще всім однаково - в одному репозиторії.

2024-10-10 15:36 UTC, mzLeVit commented
Де я можу побачити "узгоджений формат" ? Не знайшов ніякої інформації в слаку. Т.я. на мітах/колах не був, то й з інформацією, по факту, ніяк не міг бути ознайомлений. Розумію, що це вже мій фак-ап, але все ж :)

Зараз мені треба вже готовий фінальний код розбити на етапи/задачі?

2024-10-10 15:45 UTC, lexhouk commented
Нехай вже все лишається разом проте від форка я все ж казав би відмовитися. Стосовно форматів:

1. [Тут](https://python24softw-r7k7319.slack.com/archives/C07PM6YRGBZ/p1728483095648799) про розподіл.
2. [Тут](https://python24softw-r7k7319.slack.com/archives/C07PM6YRGBZ/p1728048391294319) 3-ій і 4-ий пункти і [тут](https://python24softw-r7k7319.slack.com/archives/C07PM6YRGBZ/p1728413349840409) по назвах.
3. Стосовно форків це поки лише для тебе так як ще не було таких прецедентів.

2024-10-10 15:51 UTC, mzLeVit commented
Окей, дякую, перечитаю ще раз. 

Якщо відмовлятись від форків, можна підказку як тоді краще?) Бо я весь час робив або локально і просто переносив код, або через форки.

2024-10-10 16:20 UTC, lexhouk commented
Так як дана розмова набуває вигляду організаційного характеру тому продовжуємо її в [месенджері](https://python24softw-r7k7319.slack.com/archives/C07PM6YRGBZ/p1728576056343569).

2024-10-11 09:05 UTC, lexhouk requested changes
Вітання з першим пул реквестом ще й на основі форку і для всіх задач 🔝

Проте дещо треба покращити:

1. Створити новий пул реквест безпосередньо в репозиторії з якого робився форк.
2. Підключити `pa_fileCloud` (а ще б вартувало спростити назву до `pa_file`) в `INSTALLED_APPS` з `personal_assistant/personal_assistant/settings.py`.

2024-10-11 09:05 UTC, ohorbatiuk commented on personal_assistant/pa_fileCloud/models.py
> +from cloudinary.models import CloudinaryField
Додай залежність на цей пакет у файлі `pyproject.toml` і онови після цього файл `personal_assistant/requirements.txt`.

2024-10-11 09:05 UTC, ohorbatiuk commented on personal_assistant/pa_fileCloud/models.py
Створити для цього міграцію.

2024-10-11 09:05 UTC, ohorbatiuk commented on personal_assistant/pa_fileCloud/templates/file_list.html
Зробити унаслідування від `home.html` з `pa_core`.

2024-10-11 09:05 UTC, ohorbatiuk commented on personal_assistant/pa_fileCloud/templates/upload.html
Зробити унаслідування від `form.html` з `pa_core`.

2024-10-11 09:05 UTC, ohorbatiuk commented on personal_assistant/pa_fileCloud/urls.py
> +urlpatterns = [
Підключити даний набір в `urls.py` з `personal_assistant`.

2024-10-12 12:10 UTC, lexhouk commented
Замінено [цим](https://github.com/BIN0VA/Personal-Assistant/pull/39).

2024-10-12 12:10 UTC, closed without merging