Feature/3 notes and tags
BIN0VA/Personal-Assistant pull request #38
Opened 2024-10-12 09:57 UTC by derso001

#11

2024-10-12 12:07 UTC, lexhouk requested changes
Мої вітаннячка з 1-м PR-ом! Незвична річ для Scrum Master-а але всеж.

Непоганий початок але дещо потрібно покращити:

1. Саме головне - додати посилання на свою сторінку в головне меню.
2. Стягнути останні зміни з цільової гілки і хоч там все пройде без конфлікту але треба ще змінити версію і додати себе в тому ж файлі.
3. Деякі зауваження, описані нижче, можуть повторюватися в декількох місцях але щоб не повторюватися я це не коментував кругом тож переглянь всі змінені файли на наявність проблеми.

2024-10-12 12:07 UTC, ohorbatiuk commented on personal_assistant/pa_tag/admin.py
> +from .models import Tag
Роби пропуск між власними і сторонніми залежностями:
```suggestion
from django.contrib import admin

from .models import Tag
```

2024-10-12 12:07 UTC, ohorbatiuk commented on personal_assistant/pa_tag/forms.py
Потрібний порожній рядок в кінці файлу.

2024-10-12 12:07 UTC, ohorbatiuk commented on personal_assistant/personal_assistant/settings.py
> -    'pa_contacts',
Вернути це назад.

2024-10-12 12:07 UTC, ohorbatiuk commented on personal_assistant/pa_tag/urls.py
> +    path('<int:tag_id>delete', delete, name='delete'),
Щоб все було, більш-менш, в одному стилі:
```suggestion
    path('add/', add_tag, name='create'),
    path('<int:tag_id>/', delete, name='delete'),
```

2024-10-12 12:07 UTC, ohorbatiuk commented on personal_assistant/pa_tag/urls.py
> +app_name = 'pa_tags'
Краще нехай називається як і апака - в однині:
```suggestion
app_name = 'pa_tag'
```

2024-10-12 12:07 UTC, ohorbatiuk commented on personal_assistant/personal_assistant/urls.py
> +    path('tags/', include('pa_tag.urls')),
Краще в однині:
```suggestion
    path('tag/', include('pa_tag.urls')),
```

2024-10-12 12:07 UTC, ohorbatiuk commented on personal_assistant/pa_tag/views.py
> +    return render(request, 'tags/tags.html', context)
Назвати папку як і апку:
```suggestion
    return render(request, 'pa_tag/overview.html', context)
```

2024-10-12 12:07 UTC, ohorbatiuk commented on personal_assistant/pa_tag/views.py
> +    context = {"tags":tags}
Використовувати один стиль лапок:
```suggestion
    context = {'tags': tags}
```

2024-10-12 12:07 UTC, ohorbatiuk commented on personal_assistant/pa_tag/templates/tags/tags.html
> +{% extends "pa_core/home.html" %}
Унаслідуватись від загального шаблону для сторінок із всіма сутностями певного виду і так само назвати свій шаблон для узгодженості назв:
```suggestion
{% extends 'pa_core/overview.html' %}
```

2024-10-12 12:07 UTC, ohorbatiuk commented on personal_assistant/pa_tag/templates/tags/tags.html
> +                    <i></i> Delete
Певно тег `i` мав би мати якісь класи.

2024-10-12 12:07 UTC, ohorbatiuk commented on personal_assistant/pa_tag/views.py
> +    return redirect(to='pa_tags:main')
Цей параметр - позиційний тож можна не вказувати його назву:
```suggestion
    return redirect('pa_tag:overview')
```

2024-10-12 12:07 UTC, ohorbatiuk commented on personal_assistant/pa_tag/templates/tags/add_tag.html
Оскільки ця форма дуже маленька то я б пропонував її вбудувати прямо на сторінку всіх тегів (не робити окрему сторінку на створення).

2024-10-13 21:42 UTC, derso001 commented
вніс всі зміни, що робити з цим пул реквестом далі?)

2024-10-14 14:24 UTC, lexhouk approved these changes

2024-10-14 14:26 UTC, merged